### ISSUE TITLE
Rasa PhoBert

### ISSUE THREAD

**Issue by hlong24082k** [tcong51/rasa_config_demo#1]
Em chào anh ạ,
Em hiện tại đang làm đề tài chatbot và em đang dùng rasa, sử dụng config của anh để dùng PhoBert, nhưng lại có một chút vấn đề ạ.
Em cho kết nối với Facebook, nó chỉ nhận và không trả về một câu trả lời nào.
Em không tìm thấy cách liên lạc với anh. Mong rằng sẽ nhận sự hỗ trợ từ anh.
Em cảm ơn nhiều ạ!!!

**Comment by tcong51** [comment]
Hi bạn, cảm ơn bạn đã xem.
Khi bạn sử dụng Phobert hay các phương thức pre-train khác dùng cho mô hình
để train bot. Khi có model thì sử dụng rasa shell, local để chat với bot
xem kết quả có đúng chưa. Nếu bot trả lời chính xác như bạn đã xác định,
thì việc không có câu trả lời là tại quá trình kết nối có vấn đề.
Bạn vui lòng xem lại các bước nha.
Nếu trong quá trình kết nối pipeline có lỗi thì mình sẽ hỗ trợ hết sức. Vì
mình làm cũng khá lâu rồi.
Thân,


Vào 17:04, T.4, 27 Th4, 2022 hlong24082k ***@***.***> đã viết:

**Comment by hlong24082k** [comment]
Chào anh,
Em cảm ơn anh vì sự giúp đỡ lẫn bài viết này, em đã làm được rồi ạ.
Rất cảm ơn anh.

Vào Th 4, 27 thg 4, 2022 lúc 18:16 tcong51 ***@***.***> đã
viết:

**Comment by tcong51** [comment]
Rất hân hạnh.
Chúc bạn làm bài thuận lợi.
Nếu có thắc mắc cứ việc liên hệ mình nhé.
Thân,

Vào 18:28, T.4, 27 Th4, 2022 hlong24082k ***@***.***> đã viết:
